name: IPTV Link Auto Scraper

on:
  workflow_dispatch: 
  schedule:
    - cron: '0 0 * * *' 

# এখানে গিটহাবের রানারকে সরাসরি Node 24 ব্যবহার করতে বাধ্য করা হচ্ছে
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Run IPTV Scraper Script
      run: python scraper.py

    - name: Commit and Push final playlist
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add live_*.m3u
        git commit -m "Automated Playlist Update" || echo "No changes to commit"
        git push
