name: IPTV Link Auto Scraper

on:
  workflow_dispatch: 
  schedule:
    - cron: '0 0 * * *' 

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    # এখানে ইউটিউব লিংক এক্সট্র্যাক্ট করার জন্য প্রয়োজনীয় লাইব্রেরি ইন্সটল করা হচ্ছে
    - name: Install yt-dlp
      run: |
        python -m pip install --upgrade pip
        pip install yt-dlp

    - name: Run IPTV Scraper Script
      run: python scraper.py

    - name: Commit and Push final playlist
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add live_*.m3u
        git commit -m "Automated Playlist Update with YouTube Support" || echo "No changes to commit"
        git push
